export const CREATE_ALBUM = 'CREATE_ALBUM';
export const FETCH_ALBUMS = 'FETCH_ALBUMS';
export const FETCH_ALBUM = 'FETCH_ALBUM';
export const UPDATE_ALBUM = 'UPDATE_ALBUM';
export const DELETE_ALBUM = 'DELETE_ALBUM';
export const SEARCH_ALBUM = 'SEARCH_ALBUM';
export const CHANGE_LIST_TEXT = 'CHANGE_LIST_TEXT';
